In [183]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [184]:
'''Loading Cleaned Data'''
df_clean = pd.read_csv('Railway_Cleaned.csv')

In [185]:
df_clean.head(2)

,PNR Number,Train Number,Date of Journey,Class of Travel,Quota,Source Station,Destination Station,Booking Date,Current Status,Number of Passengers,...,Travel Distance,Number of Stations,Travel Time,Train Type,Seat Availability,Special Considerations,Holiday or Peak Season,Waitlist Position,Confirmation Status,Was Waitlisted
0,PNR0000000000,51450,2024-09-01,3AC,General,NDLS,CSMT,2024-01-01,Confirmed,4,...,1656,17,37,Shatabdi,159,Senior Citizen,Yes,0,Confirmed,False
1,PNR0000000001,54807,2024-09-02,3AC,Premium Tatkal,MMCT,LTT,2024-01-02,Waitlisted,5,...,1932,18,6,Shatabdi,309,No Special Consideration,Yes,97,Not Confirmed,True

In [186]:
#Here we see Date of Journey and Booking Date are in string form so convert it into datetime 

df_clean['Date of Journey'] = pd.to_datetime(df_clean['Date of Journey'])

df_clean["Booking Date"] = pd.to_datetime(df_clean["Booking Date"])

In [187]:
'''Featuring Engineering'''

'Featuring Engineering'

In [188]:
'''Booking Time Lead'''
df_clean["Booking Lead Time"] = (df_clean["Date of Journey"] - df_clean["Booking Date"]).dt.days 
#It tellks how many days before journey ticket was booked 

df_clean.head()

,PNR Number,Train Number,Date of Journey,Class of Travel,Quota,Source Station,Destination Station,Booking Date,Current Status,Number of Passengers,...,Number of Stations,Travel Time,Train Type,Seat Availability,Special Considerations,Holiday or Peak Season,Waitlist Position,Confirmation Status,Was Waitlisted,Booking Lead Time
0,PNR0000000000,51450,2024-09-01,3AC,General,NDLS,CSMT,2024-01-01,Confirmed,4,...,17,37,Shatabdi,159,Senior Citizen,Yes,0,Confirmed,False,244
1,PNR0000000001,54807,2024-09-02,3AC,Premium Tatkal,MMCT,LTT,2024-01-02,Waitlisted,5,...,18,6,Shatabdi,309,No Special Consideration,Yes,97,Not Confirmed,True,244
2,PNR0000000002,14396,2024-09-03,3AC,Ladies,GKP,BBS,2024-01-03,RAC,5,...,4,17,Express,143,No Special Consideration,Yes,0,Confirmed,False,244
3,PNR0000000003,20295,2024-09-04,3AC,Ladies,ASR,KOAA,2024-01-04,Waitlisted,1,...,5,16,Superfast,256,Senior Citizen,No,11,Not Confirmed,True,244
4,PNR0000000004,48598,2024-09-05,2AC,Tatkal,MAS,SBC,2024-01-05,Confirmed,3,...,9,32,Express,58,No Special Consideration,Yes,0,Confirmed,False,244

In [189]:
'''Waitlist in numbers only'''

df_clean['Waitlist Number'] = (df_clean['Waitlist Position'].astype(str).str.extract(r"(\d+)")[0])

#Now convert into numeric
df_clean['Waitlist Number'] = pd.to_numeric(df_clean['Waitlist Number'])

In [190]:
'''Create Routes'''

df_clean['Route'] = df_clean['Source Station'].astype(str) + "->" + df_clean['Destination Station'].astype(str)

df_clean['Route'].head() #For checking

0    NDLS->CSMT
1     MMCT->LTT
2      GKP->BBS
3     ASR->KOAA
4      MAS->SBC
Name: Route, dtype: str

In [191]:
'''High Demand Month'''

df_clean["Journey Month"] = (df_clean["Date of Journey"].dt.month_name()) #This will extract month only

df_clean["Journey Month"].value_counts()

Journey Month
October      2563
December     2542
January      2542
March        2542
May          2542
July         2542
August       2542
September    2490
November     2460
April        2460
June         2460
February     2315
Name: count, dtype: int64

In [192]:
'''High Demand Day'''

df_clean["Journey Day"] = (df_clean["Date of Journey"].dt.day_name()) #This will extract day only

df_clean["Journey Day"].value_counts()

Journey Day
Sunday       4286
Monday       4286
Tuesday      4286
Wednesday    4286
Thursday     4286
Friday       4285
Saturday     4285
Name: count, dtype: int64

In [193]:
'''High Demand Year'''

df_clean["Journey Year"] = (df_clean["Date of Journey"].dt.year) #This will extract year only

df_clean["Journey Year"].value_counts()

Journey Year
2028    366
2032    366
2036    366
2040    366
2044    366
       ...
2102    365
2103    365
2105    365
2106    294
2024    122
Name: count, Length: 83, dtype: int64

In [194]:
'''Waitlist Category'''

df_clean['Waitlist Category'] = pd.cut(df_clean['Waitlist Number'],
                                 bins= [-1, 0, 10, 50, 100, np.inf],
                                 labels= ['No WL', 'WL 1-10', 'WL 11-50', 'WL 51-100', 'WL 100+'] )

df_clean["Waitlist Category"].value_counts()

Waitlist Category
No WL        19947
WL 100+       5008
WL 51-100     2393
WL 11-50      2122
WL 1-10        530
Name: count, dtype: int64

In [195]:
'''Booking Lead-Time Category'''

df_clean["Booking Lead Time Category"] = pd.cut(df_clean["Booking Lead Time"],
                                         bins= [-1, 1, 7, 30, 90, np.inf],
                                         labels= ["Last Minute", "2-7 Days", "8-30 Days", "31-90 Days", "90+ Days"] )

df_clean["Booking Lead Time Category"].value_counts()

Booking Lead Time Category
90+ Days       30000
Last Minute        0
2-7 Days           0
8-30 Days          0
31-90 Days         0
Name: count, dtype: int64

In [196]:
'''Distance Category'''

df_clean["Distance Category"] = pd.cut(df_clean["Travel Distance"],
                                 bins= [-1, 300, 800, 1500, np.inf],
                                 labels= ["Short", "Medium", "Long", "Very Long"] )

df_clean["Distance Category"].value_counts()

Distance Category
Long         10796
Medium        7672
Very Long     7636
Short         3896
Name: count, dtype: int64

In [197]:
'''Passenger Category'''


df_clean["Passenger Group Size"] = pd.cut(df_clean["Number of Passengers"],
                                   bins=[0, 1, 2, 4, np.inf],
                                   labels=["1 Passenger", "2 Passengers", "3-4 Passengers", "5+ Passengers"] )

df_clean["Passenger Group Size"].value_counts()

Passenger Group Size
3-4 Passengers    11966
2 Passengers       6048
5+ Passengers      6043
1 Passenger        5943
Name: count, dtype: int64

In [198]:
'''Check All New Columns'''

df_clean[
    [
        "Booking Lead Time",
        "Was Waitlisted",
        "Waitlist Number",
        "Waitlist Category",
        "Route",
        "Journey Month",
        "Journey Day",
        "Booking Lead Time Category",
        "Distance Category",
        "Passenger Group Size"
    ]
].head(10)

,Booking Lead Time,Was Waitlisted,Waitlist Number,Waitlist Category,Route,Journey Month,Journey Day,Booking Lead Time Category,Distance Category,Passenger Group Size
0,244,False,0,No WL,NDLS->CSMT,September,Sunday,90+ Days,Very Long,3-4 Passengers
1,244,True,97,WL 51-100,MMCT->LTT,September,Monday,90+ Days,Very Long,5+ Passengers
2,244,False,0,No WL,GKP->BBS,September,Tuesday,90+ Days,Short,5+ Passengers
3,244,True,11,WL 11-50,ASR->KOAA,September,Wednesday,90+ Days,Very Long,1 Passenger
4,244,False,0,No WL,MAS->SBC,September,Thursday,90+ Days,Very Long,3-4 Passengers
5,244,False,0,No WL,KOAA->MMCT,September,Friday,90+ Days,Medium,2 Passengers
6,244,False,0,No WL,ASR->PNBE,September,Saturday,90+ Days,Long,3-4 Passengers
7,244,False,0,No WL,SC->JHS,September,Sunday,90+ Days,Short,5+ Passengers
8,244,False,0,No WL,LTT->GKP,September,Monday,90+ Days,Short,1 Passenger
9,244,False,0,No WL,LKO->MAS,September,Tuesday,90+ Days,Long,1 Passenger

In [199]:
'''Check Final Structure'''

'Check Final Structure'

In [200]:
df_clean.shape

(30000, 32)

In [201]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 32 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   PNR Number                  30000 non-null  str
 1   Train Number                30000 non-null  int64
 2   Date of Journey             30000 non-null  datetime64[us]
 3   Class of Travel             30000 non-null  str
 4   Quota                       30000 non-null  str
 5   Source Station              30000 non-null  str
 6   Destination Station         30000 non-null  str
 7   Booking Date                30000 non-null  datetime64[us]
 8   Current Status              30000 non-null  str
 9   Number of Passengers        30000 non-null  int64
 10  Age of Passengers           30000 non-null  str
 11  Booking Channel             30000 non-null  str
 12  Travel Distance             30000 non-null  int64
 13  Number of Stations          30000 non-null  int64
 14  Travel Time                 30000 non-null  int64
 15  Train Type                  30000 non-null  str
 16  Seat Availability           30000 non-null  int64
 17  Special Considerations      30000 non-null  str
 18  Holiday or Peak Season      30000 non-null  str
 19  Waitlist Position           30000 non-null  int64
 20  Confirmation Status         30000 non-null  str
 21  Was Waitlisted              30000 non-null  bool
 22  Booking Lead Time           30000 non-null  int64
 23  Waitlist Number             30000 non-null  int64
 24  Route                       30000 non-null  str
 25  Journey Month               30000 non-null  str
 26  Journey Day                 30000 non-null  str
 27  Journey Year                30000 non-null  int32
 28  Waitlist Category           30000 non-null  category
 29  Booking Lead Time Category  30000 non-null  category
 30  Distance Category           30000 non-null  category
 31  Passenger Group Size        30000 non-null  category
dtypes: bool(1), category(4), datetime64[us](2), int32(1), int64(9), str(15)
memory usage: 6.2 MB

In [202]:
df_clean.isnull().sum()

PNR Number                    0
Train Number                  0
Date of Journey               0
Class of Travel               0
Quota                         0
Source Station                0
Destination Station           0
Booking Date                  0
Current Status                0
Number of Passengers          0
Age of Passengers             0
Booking Channel               0
Travel Distance               0
Number of Stations            0
Travel Time                   0
Train Type                    0
Seat Availability             0
Special Considerations        0
Holiday or Peak Season        0
Waitlist Position             0
Confirmation Status           0
Was Waitlisted                0
Booking Lead Time             0
Waitlist Number               0
Route                         0
Journey Month                 0
Journey Day                   0
Journey Year                  0
Waitlist Category             0
Booking Lead Time Category    0
Distance Category             0
Passenger Group Size          0
dtype: int64

In [203]:
'''Save The Data'''

'Save The Data'

In [204]:
df_clean.to_csv("Railway_Ticket_Analysis_Ready.csv", index=False)